# Generated by Django 5.2.4 on 2025-12-16 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='출생년도'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1, null=True, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='main_platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='주 사용 플랫폼'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='온보딩 완료 여부'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='UserGenrePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='선호 장르명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWebtoonRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webtoon_id', models.CharField(max_length=100, verbose_name='웹툰 ID')),
                ('rating', models.CharField(choices=[('BEST', '최고'), ('GOOD', '좋음'), ('BAD', '나쁨'), ('WORST', '최악'), ('WATCHED', '봤어요')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webtoon_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '유저 웹툰 평가',
                'verbose_name_plural': '유저 웹툰 평가 목록',
                'unique_together': {('user', 'webtoon_id')},
            },
        ),
    ]
