# Generated by Django 5.2.4 on 2025-12-13 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_onboarding_completed_usergenrepreference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergenrepreference',
            name='tmdb_genre_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='출생년도'),
        ),
        migrations.AddField(
            model_name='usergenrepreference',
            name='genre_name',
            field=models.CharField(default='', max_length=50, verbose_name='선호 장르명'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserWebtoonRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webtoon_id', models.CharField(max_length=100, verbose_name='웹툰 ID')),
                ('rating', models.CharField(choices=[('LIKE', '좋아요'), ('DISLIKE', '별로예요'), ('WATCHED', '봤어요')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webtoon_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '유저 웹툰 평가',
                'verbose_name_plural': '유저 웹툰 평가 목록',
                'unique_together': {('user', 'webtoon_id')},
            },
        ),
        migrations.DeleteModel(
            name='UserMovieRating',
        ),
    ]
