# Generated by Django 5.2.4 on 2025-12-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_usergenrepreference_tmdb_genre_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergenrepreference',
            name='genre_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='선호 장르명'),
        ),
    ]
