# Generated by Django 5.2.4 on 2025-12-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usergenrepreference_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='main_platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='주 사용 플랫폼'),
        ),
        migrations.AlterField(
            model_name='userwebtoonrating',
            name='rating',
            field=models.CharField(choices=[('BEST', '최고'), ('GOOD', '좋음'), ('BAD', '나쁨'), ('WORST', '최악'), ('WATCHED', '봤어요')], max_length=10),
        ),
    ]
