# Generated by Django 5.2.4 on 2025-11-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('update_days', models.CharField(max_length=50)),
                ('thumbnail', models.URLField()),
                ('url', models.URLField()),
                ('is_end', models.BooleanField(default=False)),
            ],
        ),
    ]
