# Generated by Django 5.2.4 on 2025-12-16 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SurveyCandidateWebtoon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("genre", models.CharField(blank=True, max_length=50, null=True)),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Webtoon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=15)),
                ("title", models.CharField(max_length=255, unique=True)),
                ("writers", models.CharField(blank=True, max_length=255, null=True)),
                ("painters", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "original_author",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("update_days", models.CharField(max_length=50)),
                ("thumbnail", models.URLField()),
                ("url", models.URLField()),
                ("is_adult", models.BooleanField(default=False)),
                ("synopsis", models.TextField()),
                ("is_up", models.BooleanField(default=False)),
                (
                    "favorited_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorite_webtoons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="webtoons", to="toons.genre"
                    ),
                ),
            ],
        ),
    ]
