# Generated by Django 5.2.4 on 2025-12-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCandidateWebtoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
